### ISSUE TITLE
C-a (move-to-beginning-of-line) moves wrong on wrapped line

### ISSUE THREAD

**Issue by fukamachi** [cxxxr/lem#294]
It moves to the beginning of displayed line, instead of actual line.

**Comment by fukamachi** [comment]
C-e also has the same problem except it moves the end.

**Comment by cxxxr** [comment]
fixed
https://github.com/cxxxr/lem/commit/2a110bcc8e3a73b62e47d5fe757aa72e1ecb75a2

**Comment by svetlyak40wt** [comment]
I still experience this problem on lem 1.5 (X86-64-art-osx5). Git hash is 1a3e5522.

Please, reopen this issue.

**Comment by cxxxr** [comment]
@svetlyak40wt 
Please tell me in detail the environment to reproduce.

**Comment by cxxxr** [comment]
This issue will close.
Please make a new issue if you reproduce.
