### ISSUE TITLE
opening a LISP file or trying to load a (major) mode freezes editor

### ISSUE THREAD

**Issue by the-drunk-coder** [cxxxr/lem#363]
Whenever i try to load a lisp file, or start a mode (slime or lisp-mode), the editor freezes completely and i can only close the terminal window.

Working on Arch Linux /w XTerm, SBCL 1.4.16 ... any hints ?

Best,
N

**Comment by cxxxr** [comment]
Thank you for your report.
The problem was reproduced when loading asd.

Processing can be interrupted with Control + ].

**Comment by the-drunk-coder** [comment]
Reproduced it today on macOS 10.14 as well ...

**Comment by cxxxr** [comment]
Maybe I fixed it.
https://github.com/cxxxr/lem/commit/3e52c710258bc57018f37a7a742f06689427b47a

**Comment by the-drunk-coder** [comment]
Hmm re-installed everything (deleted `.roswell`, started over), still freezes on macOS ...

**Comment by the-drunk-coder** [comment]
still happens on arch linux as well ... am i missing something, maybe ?

**Comment by the-drunk-coder** [comment]
I have to correct myself, it doesn't freeze anymore on Arch.

I had a `swank.lisp` flying around with the following content, maybe that has to do with it? It started working after deleting it and re-installing everything:

```
;; Avoid problems in realtime because the default value is :SPAWN (each
;; request in a separate thread)
#+sbcl (setf swank:*communication-style* :sigio)
;; Useful to redirect standard output from any other threads into the REPL
#+sbcl (defparameter swank:*globally-redirect-io* t)
```

**Comment by cxxxr** [comment]
Adding it to .swank.lisp freezed.
Probably it is the cause.

**Comment by the-drunk-coder** [comment]
It seems to be the second option, the first one works. 

I added this on recommendation of the Incudine mailing list, in my quest to optimize performance when doing live coding. To be honest i'm not too sure what it does ...

**Comment by cxxxr** [comment]
I'm glad that it worked well.

Since lem corresponds only to the default behavior of swank, changing variables of swank is not recommended much...

**Comment by cxxxr** [comment]
I will close issue because solved it.

**Comment by the-drunk-coder** [comment]
Oh, yes ! Sorry, forgot to close since i wanted to test it on masOS, but didn't get around to do it ...
